version: "3"
services:
    minecraft-store-backend:
        container_name: minecraft-store-backend
        build:
            context: .
            dockerfile: Dockerfile
        image: minecraft-store-backend
        env_file:
            - PROD.env
        volumes:
          - ./data/db.json:/data/db.json
        ports:
            - "2650:2650"