FROM node:17.7.2

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Bundle app source
COPY . .

EXPOSE 5000
CMD [ "npm", "run", "prod"]